/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newGUI;

/**
 *
 * @author Fuad Amin
 */
public class GIS extends javax.swing.JFrame {

   
    /**
     * Creates new form GIS
     */
    public GIS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapfrm = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        zoom = new javax.swing.JToggleButton();
        zoomout = new javax.swing.JToggleButton();
        pan = new javax.swing.JToggleButton();
        fullext = new javax.swing.JToggleButton();
        ToC = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jToolBar2 = new javax.swing.JToolBar();
        lineedt = new javax.swing.JToggleButton();
        pointedt = new javax.swing.JToggleButton();
        polyedt = new javax.swing.JToggleButton();
        sltfeature = new javax.swing.JToggleButton();
        jToolBar3 = new javax.swing.JToolBar();
        addshp = new javax.swing.JToggleButton();
        cutpoly = new javax.swing.JToggleButton();
        cutpoly1 = new javax.swing.JToggleButton();
        intersect = new javax.swing.JToggleButton();
        jToolBar4 = new javax.swing.JToolBar();
        buffer = new javax.swing.JToggleButton();
        union = new javax.swing.JToggleButton();
        panel1 = new java.awt.Panel();
        XCoord = new javax.swing.JTextField();
        YCoord = new javax.swing.JTextField();
        CoordinateLabel = new javax.swing.JTextField();
        menubar = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        save = new javax.swing.JMenuItem();
        print = new javax.swing.JMenuItem();
        property = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        edit = new javax.swing.JMenu();
        editpoint = new javax.swing.JMenuItem();
        editline = new javax.swing.JMenuItem();
        editpolygon = new javax.swing.JMenuItem();
        layer = new javax.swing.JMenu();
        addlayer = new javax.swing.JMenuItem();
        removelayer = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        javax.swing.GroupLayout mapfrmLayout = new javax.swing.GroupLayout(mapfrm.getContentPane());
        mapfrm.getContentPane().setLayout(mapfrmLayout);
        mapfrmLayout.setHorizontalGroup(
            mapfrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mapfrmLayout.setVerticalGroup(
            mapfrmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jToolBar1.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar1.setRollover(true);

        zoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/zoom-128.png"))); // NOI18N
        zoom.setText("Zoom");
        zoom.setFocusable(false);
        zoom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoom.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomActionPerformed(evt);
            }
        });
        jToolBar1.add(zoom);

        zoomout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/Zoom_out_font_awesome.svg.png"))); // NOI18N
        zoomout.setText("Zoom Out");
        zoomout.setFocusable(false);
        zoomout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(zoomout);

        pan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/775293_arrows_512x512.png"))); // NOI18N
        pan.setText("Pan");
        pan.setFocusable(false);
        pan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(pan);

        fullext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/thin-1523_target_audience_country_location-128.png"))); // NOI18N
        fullext.setText("Full Extent");
        fullext.setFocusable(false);
        fullext.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        fullext.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(fullext);

        ToC.setBackground(new java.awt.Color(255, 204, 204));

        jLabel2.setText("Table of Content (ToC)");

        javax.swing.GroupLayout ToCLayout = new javax.swing.GroupLayout(ToC);
        ToC.setLayout(ToCLayout);
        ToCLayout.setHorizontalGroup(
            ToCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToCLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        ToCLayout.setVerticalGroup(
            ToCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToCLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 468, Short.MAX_VALUE))
        );

        jToolBar2.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar2.setRollover(true);

        lineedt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/penline.png"))); // NOI18N
        lineedt.setText("Line Edit");
        lineedt.setFocusable(false);
        lineedt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lineedt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(lineedt);

        pointedt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/penpoint.png"))); // NOI18N
        pointedt.setText("Point Edit");
        pointedt.setFocusable(false);
        pointedt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pointedt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(pointedt);

        polyedt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/penpoly.png"))); // NOI18N
        polyedt.setText("Polygon Edit");
        polyedt.setFocusable(false);
        polyedt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        polyedt.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(polyedt);

        sltfeature.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/Slice-select-tool-icon.png"))); // NOI18N
        sltfeature.setText("Select Feature");
        sltfeature.setFocusable(false);
        sltfeature.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sltfeature.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(sltfeature);

        jToolBar3.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar3.setRollover(true);

        addshp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/add.png"))); // NOI18N
        addshp.setText("Add Layer");
        addshp.setFocusable(false);
        addshp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        addshp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        addshp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addshpMouseClicked(evt);
            }
        });
        addshp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addshpActionPerformed(evt);
            }
        });
        jToolBar3.add(addshp);

        cutpoly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/save-icon.png"))); // NOI18N
        cutpoly.setText("Save ");
        cutpoly.setFocusable(false);
        cutpoly.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutpoly.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(cutpoly);

        cutpoly1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/Household-Toolbox-icon.png"))); // NOI18N
        cutpoly1.setText("Save changes");
        cutpoly1.setFocusable(false);
        cutpoly1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cutpoly1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(cutpoly1);

        intersect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/Trash-Delete-icon.png"))); // NOI18N
        intersect.setText("delete feature");
        intersect.setFocusable(false);
        intersect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        intersect.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(intersect);

        jToolBar4.setBackground(new java.awt.Color(255, 255, 255));
        jToolBar4.setRollover(true);

        buffer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/database.png"))); // NOI18N
        buffer.setText("connect database");
        buffer.setFocusable(false);
        buffer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buffer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(buffer);

        union.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/export.png"))); // NOI18N
        union.setText("Export to CSV");
        union.setFocusable(false);
        union.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        union.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(union);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 835, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        XCoord.setText(" X:  ");
        XCoord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XCoordActionPerformed(evt);
            }
        });

        YCoord.setText(" Y:");

        CoordinateLabel.setBackground(new java.awt.Color(204, 204, 204));
        CoordinateLabel.setText("   COORDINATE");
        CoordinateLabel.setToolTipText("");

        file.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, 0));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/Opened-Folder-icon.png"))); // NOI18N
        jMenuItem1.setText("Open file");
        file.add(jMenuItem1);

        save.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/save-icon.png"))); // NOI18N
        save.setText("Save ");
        file.add(save);

        print.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        print.setText("Print");
        file.add(print);

        property.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        property.setText("Property");
        file.add(property);

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exit.setText("Exit");
        file.add(exit);

        menubar.add(file);

        edit.setText("Edit");

        editpoint.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        editpoint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/penpoint.png"))); // NOI18N
        editpoint.setText("Edit Point");
        edit.add(editpoint);

        editline.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, 0));
        editline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/penline.png"))); // NOI18N
        editline.setText("Edit Line");
        edit.add(editline);

        editpolygon.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, 0));
        editpolygon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seicon/penpoly.png"))); // NOI18N
        editpolygon.setText("Edit Polygon");
        edit.add(editpolygon);

        menubar.add(edit);

        layer.setText("Layer");

        addlayer.setText("Add Layer");
        layer.add(addlayer);

        removelayer.setText("Layer Remove");
        layer.add(removelayer);

        menubar.add(layer);

        jMenu1.setText("Help");
        menubar.add(jMenu1);

        setJMenuBar(menubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CoordinateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(XCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(YCoord, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(ToC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(127, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(51, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ToC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(YCoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(XCoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(CoordinateLabel))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(83, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addshpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addshpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addshpActionPerformed

    private void addshpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addshpMouseClicked


    }//GEN-LAST:event_addshpMouseClicked

    private void zoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomActionPerformed
        // TODO add your handling code here: zoomin
                    
    }//GEN-LAST:event_zoomActionPerformed

    private void XCoordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XCoordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XCoordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GIS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GIS().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CoordinateLabel;
    private javax.swing.JPanel ToC;
    private javax.swing.JTextField XCoord;
    private javax.swing.JTextField YCoord;
    private javax.swing.JMenuItem addlayer;
    private javax.swing.JToggleButton addshp;
    private javax.swing.JToggleButton buffer;
    private javax.swing.JToggleButton cutpoly;
    private javax.swing.JToggleButton cutpoly1;
    private javax.swing.JMenu edit;
    private javax.swing.JMenuItem editline;
    private javax.swing.JMenuItem editpoint;
    private javax.swing.JMenuItem editpolygon;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu file;
    private javax.swing.JToggleButton fullext;
    private javax.swing.JToggleButton intersect;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private javax.swing.JMenu layer;
    private javax.swing.JToggleButton lineedt;
    private javax.swing.JFrame mapfrm;
    private javax.swing.JMenuBar menubar;
    private javax.swing.JToggleButton pan;
    private java.awt.Panel panel1;
    private javax.swing.JToggleButton pointedt;
    private javax.swing.JToggleButton polyedt;
    private javax.swing.JMenuItem print;
    private javax.swing.JMenuItem property;
    private javax.swing.JMenuItem removelayer;
    private javax.swing.JMenuItem save;
    private javax.swing.JToggleButton sltfeature;
    private javax.swing.JToggleButton union;
    private javax.swing.JToggleButton zoom;
    private javax.swing.JToggleButton zoomout;
    // End of variables declaration//GEN-END:variables

 
    
}
